version: 2.1
jobs:
  build:
    docker:
      # - image: circleci/php:7.4-zts-buster-node-browsers-legacy
      - image: cimg/php:8.1.5
    steps:
      - checkout
      - run: sudo composer
      - run:
          working_directory: src
          command: composer update
      - run:
          working_directory: src
          command: composer install -n --prefer-dist
      - run:
          working_directory: src
          # command: npm ci
          command: npm install
      - run:
          working_directory: src
          command: npm run dev
      - run:
          working_directory: src
          command: mv .env.example .env
      - run:
          working_directory: src
          command: sudo php artisan key:generate
      - run:
          name: php test
          working_directory: src
          command: vendor/bin/phpunit
  deploy:
    docker:
      - image: circleci/php:7.4-zts-buster-node-browsers-legacy
      - image: cimg/php:8.1.5
    steps:
      - add_ssh_keys
      - run:
          name: deploy
          working_directory: ~/src
          command: |
            ssh -o StrictHostKeyChecking=no -t ec2-user@46.51.248.13 "cd portfolio && \
              git pull origin master"

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master